[package]
name = "tic"
version = "0.1.0"
authors = ["Timon Paßlick <timon.passlick@gmx.de>"]
edition = "2018"

[dependencies]
num-bigint = "0.2.2"
num-integer = "0.1.41"
num-rational = "0.2.2"
num-traits = "0.2.8"
